[package]
name = "rusttracks"
version = "0.0.1"
authors = ["Philipp BrÃ¼schweiler <blei42@gmail.com>"]

[dependencies.gtk]
path = "../dumb-gtk"

[dependencies.timerfd]
path = "../timerfd"

[dependencies]
hyper = "*"
url = "*"
rustc-serialize = "*"
